# Serves the React app through Nginx.
server {
    listen 80;

    server_name localhost;

    # Points Nginx to the built React files.
    root /usr/share/nginx/html;

    index index.html;

    # Supports React client-side routing.
    location / {
        try_files $uri /index.html;
    }
}